[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
solc = "0.8.24"

# Ignore OpenZeppelin test/certification files
ignored_error_codes = [6275]
exclude = [
    "lib/openzeppelin-contracts/certora/**",
    "lib/openzeppelin-contracts/test/**"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
